#--------PROD CONFIG -------------------------------##########
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

#resolve the issue that gateway is not aple to comminicate to Order-service after implementing spring config cloud server
eureka:
  instance:
    prefer-ip-address: false           # ✅ ensures hostname is used, not pod IP
    hostname: order-ms-app-service   # ✅ use your  order-ms-app-servicet K8s service name in deployement as hostname


