FROM openjdk:17
EXPOSE 8761
LABEL authors="aalweimine"
ADD target/geteway-service-0.0.1-SNAPSHOT.jar  geteway-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","/geteway-service-0.0.1-SNAPSHOT.jar"]